spring:
  application:
    name: psy
  profiles:
    active: h2
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3:4b

server:
  port: 8081

service:
  chat:
    mockEnabled: false
  history:
    mockEnabled: false
